spring.application.name=literalura
# Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=a1m2o0r6

# Configurações do JPA/Hibernate
# O "update" faz com que o Spring crie/atualize as tabelas automaticamente para nós
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true