# Dados de conexão
spring.datasource.url=jdbc:mysql://localhost:3306/forum_hub
spring.datasource.username=root
spring.datasource.password=a1m2o0r6

# Mostrar o SQL no console para facilitar o debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true